# Site settings
title: Cayto Nova
email: caytonova@gmail.com
description: "Cyber Security & QA Professional Portfolio."
keywords: "cybersecurity, cyber, testing, quality assurance, security, portfolio, tech"
skills: "Cybersecurity - Quality Assurance - Analyst"
meta_author: Cayto Nova
url: "https://cayto-starfield.github.io"
baseurl: "/Cyber-portfolio"
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)

# Footer settings
footer:
  copyright: Cayto Nova
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://sites.google.com/view/caytonova/home
  - title: github
    url: https://github.com/cayto-starfield

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:caytonova@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Chicagoland, Illinois

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
      
